# Generated by Django 3.2.9 on 2021-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='asthma',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_diabetic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
