# Generated by Django 3.2.9 on 2022-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20211221_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specializations',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Internal medicine', 'Internal medicine'), ('Pediatricians', 'Pediatricians'), ('Geriatric medicine', 'Geriatric medicine'), ('Allergists', 'Allergists'), ('Dermatologists', 'Dermatologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiac surgeons', 'Cardiac surgeons'), ('Ophthalmologists', 'Ophthalmologists'), ('Orthopedic surgeons', 'Orthopedic surgeons'), ('Obstetrician/gynecologists', 'Obstetrician/gynecologists'), ('General surgeons', 'General surgeons'), ('Cardiologists', 'Cardiologists'), ('Endocrinologists', 'Endocrinologists'), ('Rheumatologists', 'Rheumatologists'), ('Radiologists', 'Radiologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Oncologists', 'Oncologists'), ('Nephrologists', 'Nephrologists'), ('Urologists', 'Urologists'), ('Pulmonologists', 'Pulmonologists'), ('Psychiatrists', 'Psychiatrists'), ('Otolaryngologists', 'Otolaryngologists'), ('Neurologists', 'Neurologists')], default='Internal medicine', max_length=50),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
